# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/joeconlin"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://linkedin.com/jtconlin"

[social.params]
icon = "brand-linkedin"
